# Generated by Django 5.2.17 on 2026-08-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateField(blank=True, null=True, verbose_name='appeared_at'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateField(blank=True, null=True, verbose_name='disappeared_at'),
        ),
    ]
