# Generated by Django 5.2.17 on 2026-08-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_remove_pokemon_title_pokemon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='title',
            field=models.CharField(default='default_name', max_length=200, verbose_name='pokemon_name'),
            preserve_default=False,
        ),
    ]
