# Generated by Django 5.2.17 on 2026-08-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemon_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PkemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longetude', models.FloatField(verbose_name='longetude')),
            ],
        ),
    ]
