# Generated by Django 5.2.17 on 2026-08-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pkemonentity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PkemonEntity',
            new_name='PokemonEntity',
        ),
    ]
