# Generated by Django 5.2.17 on 2026-08-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemonentity_attack_pokemonentity_defense_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='attack',
            new_name='strength',
        ),
    ]
